Sahila
cewonkece
Invisible

Sahila — 15/10/2025 0:24
Belum ada
Sahila — 15/10/2025 0:24
Asik
k — 15/10/2025 0:25
tapi masih gini
Image
wait gw mau coba push, ntr lu pake gradien yang ada di base.html nya
udah gw merge
Sahila — 15/10/2025 0:30
Eh gw gak bisa pull dh
k — 15/10/2025 0:30
kok bisa
Sahila — 15/10/2025 0:32
udah bs
vscode gw aneh tadi
lagi ngedit ga
k — 15/10/2025 0:33
udah si
gw pgn buat navbar
atau section bwhnya
Sahila — 15/10/2025 0:35
gw lagi ngerjain yang section bawahnya 
k — 15/10/2025 0:35
maksudnya
bawah lu bawah lagi
Sahila — 15/10/2025 0:35
yg your game your space
k — 15/10/2025 0:36
itu bila
gw bawah lagi
Sahila — 15/10/2025 0:36
eh
bikelah
yang mana yang blm ada yang ngerjain
k — 15/10/2025 0:37
event feature sama footer
Sahila — 15/10/2025 0:37
ok gw event feature
k — 15/10/2025 0:37
okeh
Sahila — 15/10/2025 0:39
lu masi lanjut ngerjain gk sampe nanti
k — 15/10/2025 0:40
mngkin iya klo gw gk ketiduran
nanggung soalnya
Sahila — 15/10/2025 0:41
pengen ngubah" tapi takut nabrak
k — 15/10/2025 0:41
lu mau ubahygmna
Sahila — 15/10/2025 0:41
features preview dikit sm nambahin event
k — 15/10/2025 0:42
gpp gasi itu
gw ga nyentuh itu
Sahila — 15/10/2025 0:42
oh okok
k — 15/10/2025 0:42
nambahin event ygmna
Sahila — 15/10/2025 0:42
event feature
k — 15/10/2025 0:42
ooooh
Sahila — 15/10/2025 10:37
commit gw muncul ga
Sahila — 15/10/2025 11:45
cara biar gradient backgroundnya muncul kayak section booking gimana ya
gradient-overlay juga?
k — 15/10/2025 11:56
muncul
k — 15/10/2025 11:57
hooh tp itu hrs di setting lgi deh
Sahila — 15/10/2025 11:57
udh di solve sm bila
k — 15/10/2025 12:33
asiap
k — 06/11/2025 21:34
Forwarded
yasin https://drive.google.com/drive/folders/10rPXIHUatG9bzagRIbwlz06a-QbKLaoi
Google Drive
k — 25/11/2025 12:51
#315672
#293241
Sahila — 25/11/2025 13:10
Image
Image
Image
k — Yesterday at 15:36
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
Expand
pubspec.lock
14 KB
Sahila — 19:39
import 'package:flutter/material.dart';
import 'package:pbp_django_auth/pbp_django_auth.dart';
import 'package:provider/provider.dart';

import 'package:any_venue/main.dart';
import 'package:any_venue/widgets/confirmation_modal.dart';
Expand
message.txt
24 KB
k — 20:01
import 'package:flutter/material.dart';
import 'package:pbp_django_auth/pbp_django_auth.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:any_venue/main.dart';
import 'package:any_venue/widgets/confirmation_modal.dart';
import 'package:any_venue/widgets/toast.dart';
import 'package:any_venue/widgets/components/app_bar.dart';

import 'package:any_venue/venue/models/venue.dart';
import 'package:any_venue/venue/screens/venue_form.dart';
import 'package:any_venue/venue/widgets/venue_detail_widgets.dart';

import 'package:any_venue/review/screens/review_page.dart';
import 'package:any_venue/review/screens/review_form.dart';
import 'package:any_venue/review/models/review.dart';
import 'package:any_venue/review/widgets/review_list.dart';

class VenueDetail extends StatefulWidget {
  final Venue venue;
  const VenueDetail({super.key, required this.venue});

  @override
  State<VenueDetail> createState() => _VenueDetailState();
}

class _VenueDetailState extends State<VenueDetail> {
  late Venue _venue;
  bool _hasEdited = false;
  bool _isDeleting = false;

  List<Review> _reviews = [];
  bool _isLoadingReviews = true;

  @override
  void initState() {
    super.initState();
    _venue = widget.venue;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final request = context.read<CookieRequest>();
      _fetchReviews(request);
    });
  }

  // --- API LOGIC ---
  Future<void> _fetchReviews(CookieRequest request) async {
    try {
      final response = await request.get(
        'https://keisha-vania-anyvenue.pbp.cs.ui.ac.id/review/json/venue/${_venue.id}/',
      );
      if (mounted) {
        setState(() {
          List<dynamic> listJson = response;
          _reviews = listJson.map((d) => Review.fromJson(d)).toList();
          _isLoadingReviews = false;
        });
      }
    } catch (e) {
      debugPrint("Failed to fetch review: $e");
      if (mounted) setState(() => _isLoadingReviews = false);
    }
  }

  // Fungsi Delete Review
  Future<void> _handleDeleteReview(Review review, CookieRequest request) async {
    // 1. Tampilkan Modal Konfirmasi
    ConfirmationModal.show(
      context,
      title: "Delete Review?",
      message: "Are you sure you want to delete your review?",
      isDanger: true,
      confirmText: "Delete",
      icon: Icons.delete_outline_rounded,
      onConfirm: () async {
        // 2. Request ke Django
        final response = await request.post(
          'https://keisha-vania-anyvenue.pbp.cs.ui.ac.id/review/delete-flutter/${review.id}/',
          {},
        );

        if (context.mounted) {
          if (response['status'] == 'success') {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text("Review deleted successfully")),
            );
            // 3. Refresh list review agar item hilang
            _fetchReviews(request);
          } else {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(response['message'] ?? "Failed to delete"),
              ),
            );
          }
        }
      },
    );
  }

... (314 lines left)
Collapse
message.txt
15 KB
﻿
k
kurrorro
 
 
 
import 'package:flutter/material.dart';
import 'package:pbp_django_auth/pbp_django_auth.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:any_venue/main.dart';
import 'package:any_venue/widgets/confirmation_modal.dart';
import 'package:any_venue/widgets/toast.dart';
import 'package:any_venue/widgets/components/app_bar.dart';

import 'package:any_venue/venue/models/venue.dart';
import 'package:any_venue/venue/screens/venue_form.dart';
import 'package:any_venue/venue/widgets/venue_detail_widgets.dart';

import 'package:any_venue/review/screens/review_page.dart';
import 'package:any_venue/review/screens/review_form.dart';
import 'package:any_venue/review/models/review.dart';
import 'package:any_venue/review/widgets/review_list.dart';

class VenueDetail extends StatefulWidget {
  final Venue venue;
  const VenueDetail({super.key, required this.venue});

  @override
  State<VenueDetail> createState() => _VenueDetailState();
}

class _VenueDetailState extends State<VenueDetail> {
  late Venue _venue;
  bool _hasEdited = false;
  bool _isDeleting = false;

  List<Review> _reviews = [];
  bool _isLoadingReviews = true;

  @override
  void initState() {
    super.initState();
    _venue = widget.venue;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final request = context.read<CookieRequest>();
      _fetchReviews(request);
    });
  }

  // --- API LOGIC ---
  Future<void> _fetchReviews(CookieRequest request) async {
    try {
      final response = await request.get(
        'https://keisha-vania-anyvenue.pbp.cs.ui.ac.id/review/json/venue/${_venue.id}/',
      );
      if (mounted) {
        setState(() {
          List<dynamic> listJson = response;
          _reviews = listJson.map((d) => Review.fromJson(d)).toList();
          _isLoadingReviews = false;
        });
      }
    } catch (e) {
      debugPrint("Failed to fetch review: $e");
      if (mounted) setState(() => _isLoadingReviews = false);
    }
  }

  // Fungsi Delete Review
  Future<void> _handleDeleteReview(Review review, CookieRequest request) async {
    // 1. Tampilkan Modal Konfirmasi
    ConfirmationModal.show(
      context,
      title: "Delete Review?",
      message: "Are you sure you want to delete your review?",
      isDanger: true,
      confirmText: "Delete",
      icon: Icons.delete_outline_rounded,
      onConfirm: () async {
        // 2. Request ke Django
        final response = await request.post(
          'https://keisha-vania-anyvenue.pbp.cs.ui.ac.id/review/delete-flutter/${review.id}/',
          {},
        );

        if (context.mounted) {
          if (response['status'] == 'success') {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text("Review deleted successfully")),
            );
            // 3. Refresh list review agar item hilang
            _fetchReviews(request);
          } else {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(response['message'] ?? "Failed to delete"),
              ),
            );
          }
        }
      },
    );
  }

  Future<void> _refreshData() async {
    final request = context.read<CookieRequest>();
    try {
      final response = await request.get(
        'https://keisha-vania-anyvenue.pbp.cs.ui.ac.id/venue/api/venue-detail-flutter/${_venue.id}/',
      );
      if (mounted) {
        setState(() => _venue = Venue.fromJson(response));
      }
    } catch (e) {
      debugPrint("Failed to refresh data: $e");
    }
  }

  Future<void> _handleDelete() async {
    final request = context.read<CookieRequest>();

    await ConfirmationModal.show(
      context,
      title: "Delete Venue?",
      message:
          "Are you sure you want to delete this venue? This action cannot be undone.",
      isDanger: true,
      confirmText: "Delete",
      icon: Icons.delete_outline_rounded,
      onConfirm: () async {
        final response = await request.post(
          'https://keisha-vania-anyvenue.pbp.cs.ui.ac.id/venue/api/delete-flutter/${_venue.id}/',
          {},
        );

        if (!mounted) return;

        if (response['status'] == 'success') {
          CustomToast.show(context, message: "Venue deleted!", isError: false);

          setState(() => _isDeleting = true);
          await Future.delayed(const Duration(milliseconds: 350));

          if (!mounted) return;
          Navigator.pop(
            context,
            true,
          ); // <-- ini yang dibaca VenueList untuk refresh
        } else {
          CustomToast.show(
            context,
            message: "Failed to delete.",
            isError: true,
          );
        }
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final request = context.watch<CookieRequest>();
    final String currentUsername = request.jsonData['username'] ?? '';
    final String currentRole = request.jsonData['role'] ?? 'USER';

    final bool isMyVenue = currentUsername == _venue.owner.username;
    final bool isUserRole = currentRole == 'USER';

    // Cari review user
    Review? userReview;
    if (!_isLoadingReviews && _reviews.isNotEmpty) {
      try {
        userReview = _reviews.firstWhere((r) => r.user == currentUsername);
      } catch (_) {
        // Tidak ditemukan review milik user ini
        userReview = null;
      }
    }

    final bool hasReviewed = userReview != null;

    return PopScope(
      canPop: _isDeleting,
      onPopInvoked: (didPop) {
        if (didPop) return;

        if (context.mounted) {
          Navigator.pop(context, _hasEdited);
        }
      },
      child: Scaffold(
        backgroundColor: Colors.white,
        appBar: const CustomAppBar(title: "Detail Venue"),
        body: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // 1. Header Image
                    VenueHeaderImage(
                      imageUrl:
                          'https://keisha-vania-anyvenue.pbp.cs.ui.ac.id/venue/proxy-image/?url=${Uri.encodeComponent(_venue.imageUrl)}',
                    ),

                    Padding(
                      padding: const EdgeInsets.all(24.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          // 2. Title
                          Text(
                            _venue.name,
                            style: GoogleFonts.nunitoSans(
                              fontSize: 24,
                              fontWeight: FontWeight.w800,
                              color: const Color(0xFF293241),
                              height: 1.2,
                            ),
                          ),
                          const SizedBox(height: 24),

                          // 3. Info Card
                          VenueInfoCard(venue: _venue),
                          const SizedBox(height: 24),

                          // 4. Owner Profile
                          VenueOwnerSection(username: _venue.owner.username),
                          const SizedBox(height: 24),

                          // 5. Description & Location
                          _buildSectionTitle("Description"),
                          Text(
                            _venue.description,
                            style: const TextStyle(
                              color: Colors.grey,
                              height: 1.6,
                              fontSize: 14,
                            ),
                          ),
                          const SizedBox(height: 20),
                          _buildSectionTitle("Location"),
                          Text(
                            _venue.address,
                            style: const TextStyle(
                              color: Colors.grey,
                              height: 1.6,
                              fontSize: 14,
                            ),
                          ),
                          const SizedBox(height: 32),

                          // 6. Review Header
                          _buildReviewHeader(context),

                          // 7. Review List
                          if (_isLoadingReviews)
                            const SizedBox(
                              height: 150,
                              child: Center(
                                child: CircularProgressIndicator(
                                  color: MyApp.orange,
                                ),
                              ),
                            )
                          else if (_reviews.isEmpty)
                            Container(
                              height: 150,
                              width: double.infinity,
                              alignment: Alignment.center,
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: const [
                                  Text(
                                    "No reviews for this venue yet.",
                                    style: TextStyle(color: Colors.grey),
                                  ),
                                ],
                              ),
                            )
                          else
                            ReviewList(
                              reviews: _reviews,
                              isHorizontal: true,
                              scrollable: true,
                              currentUsername:
                                  currentUsername, // Diambil dari variabel yang sudah kamu deklarasikan di awal build
                              // Callback Edit
                              onEdit: (review) async {
                                // Navigasi ke Form Edit
                                final result = await Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                    builder: (context) => ReviewFormPage(
                                      existingReview:
                                          review, // Kirim objek review untuk diedit
                                    ),
                                  ),
                                );
                                // Jika sukses edit (return true), refresh data
                                if (result == true && context.mounted) {
                                  _fetchReviews(request);
                                }
                              },

                              // Callback Delete
                              onDelete: (review) {
                                _handleDeleteReview(review, request);
                              },
                            ),

                          const SizedBox(height: 100),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),

            // 8. Bottom Action Buttons
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: Colors.white,
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.05),
                    blurRadius: 20,
                    offset: const Offset(0, -5),
                  ),
                ],
              ),
              child: SafeArea(
                child: VenueActionButtons(
                  isMyVenue: isMyVenue,
                  isUserRole: isUserRole,
                  hasReviewed: userReview != null,
                  onDelete: _handleDelete,
                  onBook: () {
                    /* Todo: Booking Logic */
                  },
                  onEdit: () async {
                    final result = await Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => VenueFormPage(venue: _venue),
                      ),
                    );
                    if (result == true) {
                      setState(() => _hasEdited = true);
                      await _refreshData();
                    }
                  },
                  onReview: () async {
                    // Panggil Form
                    final result = await Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => ReviewFormPage(
                          // Jika Edit -> kirim existingReview
                          // Jika Add  -> kirim venueId
                          venueId: hasReviewed ? null : _venue.id,
                          existingReview: userReview,
                        ),
                      ),
                    );
                    if (result == true && mounted) _fetchReviews(request);
                  },
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Text(
        title,
        style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
      ),
    );
  }

  Widget _buildReviewHeader(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        const Text(
          "Customer Reviews",
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
        ),
        GestureDetector(
          onTap: () => Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => ReviewPage(venueId: _venue.id),
            ),
          ),
          child: const Text(
            "See all",
            style: TextStyle(
              fontSize: 13,
              color: MyApp.orange,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
      ],
    );
  }
}